import os

os.environ.setdefault("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/job_hunt_crew?schema=public")
os.environ.setdefault("S3_ENDPOINT", "http://localhost:9000")
os.environ.setdefault("S3_REGION", "us-east-1")
os.environ.setdefault("S3_BUCKET", "job-hunt-crew")
os.environ.setdefault("S3_FORCE_PATH_STYLE", "true")
os.environ.setdefault("S3_ACCESS_KEY_ID", "minioadmin")
os.environ.setdefault("S3_SECRET_ACCESS_KEY", "minioadmin")
os.environ.setdefault("SQS_ENDPOINT", "http://localhost:9324")
os.environ.setdefault("SQS_REGION", "us-east-1")
os.environ.setdefault("SQS_ANALYSIS_INTAKE_QUEUE_URL", "http://localhost:9324/000000000000/analysis-intake")
os.environ.setdefault("SQS_CV_CONVERSION_QUEUE_URL", "http://localhost:9324/000000000000/cv-conversion")
os.environ.setdefault("SQS_ACCESS_KEY_ID", "x")
os.environ.setdefault("SQS_SECRET_ACCESS_KEY", "x")
