import { existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";

// next/font/google reaches the network at module-eval time; the visual base only
// needs the returned CSS-variable name, so stub it.
vi.mock("next/font/google", () => ({
  Inter: () => ({ variable: "--font-inter", className: "" }),
  Source_Serif_4: () => ({ variable: "--font-source-serif", className: "" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono", className: "" }),
}));

describe("root metadata", () => {
  it("uses the real product name, not the create-next-app template", async () => {
    const { metadata } = await import("../app/layout");
    const title = JSON.stringify(metadata.title);
    expect(title).toContain("Job Hunt Crew");
    expect(title).not.toContain("Create Next App");
  });

  it("has a real description, not the create-next-app template", async () => {
    const { metadata } = await import("../app/layout");
    expect(metadata.description).toBeTruthy();
    expect(metadata.description).not.toMatch(/generated by create next app/i);
  });
});

describe("template assets", () => {
  it("no create-next-app SVGs are left in public/", () => {
    const publicDir = join(__dirname, "..", "public");
    for (const svg of [
      "next.svg",
      "vercel.svg",
      "file.svg",
      "globe.svg",
      "window.svg",
    ]) {
      expect(existsSync(join(publicDir, svg))).toBe(false);
    }
  });

  it("globals.css no longer hard-codes Arial over the font setup", async () => {
    const { readFile } = await import("node:fs/promises");
    const css = await readFile(
      join(__dirname, "..", "app", "globals.css"),
      "utf8",
    );
    expect(css).not.toMatch(/font-family:\s*Arial/i);
  });
});

describe("design system foundations", () => {
  it("DESIGN.md exists", () => {
    expect(existsSync(join(__dirname, "..", "DESIGN.md"))).toBe(true);
  });

  it("globals.css declares the type-scale, elevation, and motion tokens", async () => {
    const { readFile } = await import("node:fs/promises");
    const css = await readFile(
      join(__dirname, "..", "app", "globals.css"),
      "utf8",
    );
    for (const token of [
      "--text-base",
      "--text-3xl",
      "--shadow-sm",
      "--shadow-lg",
      "--ease-standard",
      "--duration-base",
    ]) {
      expect(css).toContain(token);
    }
  });
});
